### ISSUE TITLE
Spring Boot日志管理

### ISSUE THREAD

**Issue by pycrab** [pycrab/crab-blog#24]
## Spring Boot日志管理
> Spring Boot集成slf4j和log4j2

---
### 简介
首先给个Spring Boot的官方文档入口地址，[版本地址](https://spring.io/projects/spring-boot/#learn)，进入之后选择你需要的版本，点击Reference Doc.，然后点击Documentation Overview，可以看到有PDF的选项，打开就可以下载PDF文件啦。

查看Spring Boot Reference官网文档如下：
```text
4.4. Logging
Spring Boot uses Commons Logging for all internal logging but leaves the underlying log implementation open. Default configurations are provided for Java Util Logging, Log4J2, and Logback. In each case, loggers are pre-configured to use console output with optional file output also available.
By default, if you use the “Starters”, Logback is used for logging. Appropriate Logback routing is also included to ensure that dependent libraries that use Java Util Logging, Commons Logging, Log4J, or SLF4J all work correctly.
There are a lot of logging frameworks available for Java. Do not worry if the above list seems confusing. Generally, you do not need to change your logging dependencies and the Spring Boot defaults work just fine.
```
以上得知，Spring Boot默认使用Commons-logging日志门面来管理日志，同时也提供了常见的日志框架的默认配置。如果我们使用的是Starter依赖，比如spring-boot-starter-web，我们可以看到其包含了spring-boot-starter-logging依赖，这使得Spring Boot使用slf4j和Logback来管理日志。同时Spring Boot也指明通常没必要改变日志的依赖，默认的就挺好的。
```text
9.8.2. Configure Log4j for Logging
Spring Boot supports Log4j 2 for logging configuration if it is on the classpath. If you use the starters for assembling dependencies, you have to exclude Logback and then include log4j 2 instead. If you do not use the starters, you need to provide (at least) spring-jcl in addition to Log4j 2.
```
继续看文档可以知道Spring Boot给我们提供了如何改变默认的日志框架的方法，下面我们实践一下Spring Boot如何使用slf4j加log4j2这个组合。

---
### slf4j与log4j2
1. pom依赖管理
- 排除Starter默认的依赖
	```java
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    ```
- 引入log4j2的依赖以及yml文件支持依赖
	```java
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-log4j2</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-yaml</artifactId>
    </dependency>
    ```
修改完依赖，接下来进行日志配置，我们使用yml文件进行配置（既然提供yml文件支持，那就使用吧）

2. yml配置文件
首先给个log4j2官方文档PDF地址，[2.x版本在这里](http://logging.apache.org/log4j/2.x/log4j-users-guide.pdf)。根据文档说明进行配置，其中，配置输出的官方文档地址为[Appenders](http://logging.apache.org/log4j/2.x/manual/appenders.html)。首先在项目resources文件夹下创建log4j2.yml文件：
    ```yml
    Configuration:
      status: warn
      name: Log4j2Config

      Properties:
        Property:
          -
            name: InfoFile
            value: /var/info
          -
            name: ErrorFile
            value: /var/error/error.log

      Loggers:
        Root:
          level: info
          AppenderRef:
            - ref: STDOUT
            - ref: Async

      Appenders:
        Console:
          -
            name: STDOUT
            target: SYSTEM_OUT
            PatternLayout:
              pattern: "%d{DEFAULT} %highlight{%-5p} %style{[%t]:}{Blue} %-80m %style{%-36c{1.}}{Yellow} %style{%F}{Blue}:%style{%L}{Magenta}->%style{%M}{Bright} %style{%C}{yellow}%n"
        File:
          name: errorFile
          fileName: ${ErrorFile}
          Filters:
            ThresholdFilter:
              level: error
              onMatch: ACCEPT
              onMismatch: DENY
          ignoreExceptions: false
          PatternLayout:
            pattern: "%d{DEFAULT} %-5p [%t]: %m :%c:%l%n"
    #      默认
    #      append: true
    #      bufferedIO: true
    #      bufferSize: 4096
    #      createOnDemand: false
    #      locking: false
        RollingFile:
          name: rollingFile
          fileName: ${InfoFile}/info.log
          Filters:
            ThresholdFilter:
              level: info
              onMatch: ACCEPT
              onMismatch: DENY
          Policies:
            SizeBasedTriggeringPolicy:
              size: "50MB"
          DefaultRolloverStrategy:
            max: 50
          ignoreExceptions: false
          filePattern: "${InfoFile}/$${date:yyyy-MM}/info-%d{yyyyMMdd}-%i.log"
          PatternLayout:
            pattern: "%d{DEFAULT} %-5p [%t]: %m :%c:%l%n"
        Async:
          name: Async
          AppenderRef:
            - ref: errorFile
            - ref: rollingFile
    #    SMTP:
    #      name: SMTP
    #      from:
    #      to:
    #      subject: Error Log
    #      smtpHost:
    #      smtpPort:
    #      smtpUsername:
    #      smtpPassword:
    ```
该文件可以作为通用日志配置文件，可以根据需要进行修改。
配置文件有了，使用Spring Boot进行多环境日志输出时，需要在application-{profile}.yml文件中进行配置，配置如下：
```yml
logging:
  level:
    root: info
    com:
      crab: error
```
对于每个不同的环境只需要修改root对应的level，还可以针对不同的包或者类进行不同层级的划分，比如上面的com.crab包配置error层级。
注意：Spring Boot使用log4j2需要如上配置，与logback不同（logback默认配置是logging.pattern.level），这些文档中都有。

3. 在项目中使用，推荐使用占位符填充变量，案例如下：
    ```java
    public class Demo {
        private static final Logger logger = LoggerFactory.getLogger("Demo");
        public void demoTest(String arg1, String arg2) {
            logger.info("info {}", arg1);
            logger.error("error {}", arg2);
        }
    }
    ```
运行测试案例，可以看到控制台打印出了日志，项目根目录也产生了对应的日志文件。

对了，IDEA默认没有彩色日志，虽然日志文件中配置了彩色高亮，需要在项目的Edit Configurations中，在该项目的Enviroment中配置VM options添加`-Dlog4j.skipJansi=false`，之后就有彩色日志了。
